"""Print session summaries for screenshot."""

from datetime import datetime

def log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] [ ] {msg}")

print()
log("=" * 52)
log("PAPER TRADING — SESSION COMPARISON")
log("=" * 52)
print()
log("STRATEGY 1: Flash Crash (algorithmic)")
log("-" * 52)
log("Coin:       ETH")
log("Trades:     15")
log("Wins:       2  | Losses: 13")
log("Win rate:   13.3%")
log("Total PnL:  -$26.21")
log("AI:         none")
print()
log("STRATEGY 2: Claude Haiku (AI decision engine)")
log("-" * 52)
log("Coin:       ETH")
log("Trades:     17")
log("Wins:       9  | Losses: 8")
log("Win rate:   52.9%")
log("Total PnL:  +$7.29")
log("AI calls:   17 | AI cost: $0.0300")
log("Confidence: 70% threshold")
log("TP: +0.08  | SL: -0.04")
print()
log("=" * 52)
log("AI win rate:  4x better (53% vs 13%)")
log("AI PnL:       +$33.50 vs baseline")
log("AI cost:      $0.03 total")
log("=" * 52)
print()
